### ISSUE TITLE
[SMTChecker] Crash in `Z3CHCInterface::query()` when running isoltest on Ubuntu

### ISSUE THREAD

**Issue by benbaley** [ethereum/solidity#11676]
## Description

when I build solidity of v0.8.6 and run the `scripts/isoltest.sh` with libevmone.so.0.7.0, the following error occur:

```
...
ABIJson/multiple_methods_order.sol: OK
ABIJson/inherited.sol: OK
ABIJson/multiple_params.sol: OK
ABIJson/events_anonymous.sol: OK
ABIJson/global_struct.sol: OK
ABIJson/receive_ether_function.sol: OK
ABIJson/events.sol: OK
ABIJson/payable_constructor_abi.sol: OK

JSON ABI Test Summary: 32/32 tests successful.

smtCheckerTests/array_members/push_as_lhs_and_rhs_1d.sol: OK
smtCheckerTests/array_members/push_storage_ref_unsafe_length.sol: Segmentation fault (core dumped)
```

stacktrace:
```
gdb ./build/test/tools/isoltest core
GNU gdb (Ubuntu 9.2-0ubuntu2) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/test/tools/isoltest...
(No debugging symbols found in ./build/test/tools/isoltest)
[New LWP 20716]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./scripts/../build/test/tools/isoltest --testpath ./scripts/../test'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f516225c824 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
(gdb) bt
#0  0x00007f516225c824 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#1  0x00007f51622648e4 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#2  0x00007f5162264e81 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#3  0x00007f5162266782 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#4  0x00007f5162f490e2 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#5  0x00007f5162f4a32a in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#6  0x00007f5162ea3675 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#7  0x00007f5162eb16e9 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#8  0x00007f5162ec1089 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#9  0x00007f5162cf7cf5 in ?? () from /lib/x86_64-linux-gnu/libz3.so.4
#10 0x00007f516303e577 in Z3_fixedpoint_get_answer () from /lib/x86_64-linux-gnu/libz3.so.4
#11 0x0000564d277b6169 in solidity::smtutil::Z3CHCInterface::query(solidity::smtutil::Expression const&) ()
#12 0x0000564d27400711 in solidity::frontend::CHC::query(solidity::smtutil::Expression const&, solidity::langutil::SourceLocation const&) ()
#13 0x0000564d2740b491 in solidity::frontend::CHC::checkAndReportTarget(solidity::frontend::CHC::CHCVerificationTarget const&, solidity::langutil::ErrorId, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#14 0x0000564d27416704 in solidity::frontend::CHC::checkVerificationTargets() ()
#15 0x0000564d27418305 in solidity::frontend::CHC::analyze(solidity::frontend::SourceUnit const&) ()
#16 0x0000564d27113801 in solidity::frontend::ModelChecker::analyze(solidity::frontend::SourceUnit const&) ()
#17 0x0000564d27198487 in solidity::frontend::CompilerStack::analyze() ()
#18 0x0000564d2702a7e0 in solidity::frontend::test::SyntaxTest::parseAndAnalyze() ()
#19 0x0000564d270560f9 in solidity::frontend::test::SMTCheckerTest::run(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#20 0x0000564d26fa870d in TestTool::process() ()
#21 0x0000564d26fa951f in TestTool::processPath(std::unique_ptr<solidity::frontend::test::TestCase, std::default_delete<solidity::frontend::test::TestCase> > (*)(solidity::frontend::test::TestCase::Config const&), solidity::test::IsolTestOptions const&, boost::filesystem::path const&, boost::filesystem::path const&) ()
#22 0x0000564d26f8b31b in main ()
```
## Environment

- Compiler version:v0.8.6 commit 11564f7ec2d34f488e7f7946c1f19491a967370e
- Target EVM version (as per compiler settings): 
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu20.10

## Steps to Reproduce

1. sh scripts/build.sh
2. sh scripts/isoltest.sh

**Comment by leonardoalt** [comment]
Hi @benbaley , thanks for reporting!
Unfortunately this crash comes from z3 and there's not much we can do about it, other than reporting the issue (which we already did). What's your z3 version? Our tests require the latest z3 release (4.8.12 right now) to pass, and they don't crash on Ubuntu/Arch Linux/OSX currently. Maybe updating z3 would help if it's possible?

**Comment by leonardoalt** [comment]
Closing since this should hopefully be fine with the latest z3 release. Please reopen if needed.
