### ISSUE TITLE
SMTChecker unexpected errors in Windows and Mac

### ISSUE THREAD

**Issue by acmRecife** [ethereum/solidity#13198]
Context: I am running SMTChecker on a contract written in Solidity v0.8.10. I tried both in Windows and Mac and the following situations happened:

Windows: 11 Pro, 16GB Core i7
Using hardhat, command: npx hardhat compile

For this SMTChecker configuration

modelChecker: {
        engine: 'chc',
        timeout: 50, // <=== This is tiny because my project is big
        targets: ['overflow']
      }

, I got the following report:

Unknown exception during compilation: Dynamic exception type: class std::bad_alloc
asks\compile.ts:468:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Environment._runTaskDefinition (C:\Users\me\Desktop\Desktop\sc_solidity-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at async OverriddenTaskDefinition._action (C:\Users\me\Desktop\Desktop\sc_solidity-contracts\node_modules\@typechain\hardhat\src\index.ts:30:30)    at async Environment._runTaskDefinition (C:\Users\me\Desktop\Desktop\sc_solidity-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at async Environment.run (C:\Users\me\Desktop\Desktop\sc_solidity-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (C:\Users\me\Desktop\Desktop\sc_solidity-contracts\node_modules\hardhat\src\builtin-tasks\compile.ts:1349:63)
    at async Environment._runTaskDefinition (C:\Users\me\Desktop\Desktop\sc_solidity-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at async Environment.run (C:\Users\me\Desktop\Desktop\sc_solidity-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:129:14)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
MacOS: 12.4 Monterey, 8GB Core i7
Using hardhat, command: npx hardhat compile

For this SMTChecker configuration

modelChecker: {
        engine: 'bmc',
        targets: ['overflow'],
        timeout: 50, // <=== This is tiny because my project is big
        showUnproved: true
      }

, I got the following report:

An unexpected error occurred:

Error: Command failed: /Users/alexandremota/Library/Caches/hardhat-nodejs/compilers/macosx-amd64/solc-macosx-amd64-v0.8.10+commit.fc410830 --standard-json

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: null,
  killed: false,
  signal: 'SIGKILL',
  cmd: '/Users/me/Library/Caches/hardhat-nodejs/compilers/macosx-amd64/solc-macosx-amd64-v0.8.10+commit.fc410830 --standard-json'
}
npx hardhat compile  8707,59s user 8334,31s system 70% cpu 6:45:41,24 total

Could you please give me some advice to work around these? Thanks!

**Comment by leonardoalt** [comment]
Hi @acmRecife , thanks for reporting.
As a quick attempt, can you try the OSX version with the latest compiler release (0.8.15)?

**Comment by acmRecife** [comment]
I will try, @leonardoalt . This project is based on hardhat and other technologies and I am not sure how to adjust the environment to consider v0.8.15, but I will try. Best!

**Comment by acmRecife** [comment]
Hi @leonardoalt . I got the project to be compiled by v0.8.15 and the above error disappeared. In particular, now I can use timeout: 0 for the outOfBounds target property. But a curious fact just emerged:

Warning: CHC: Out of bounds access might happen here.
  --> @openzeppelin/contracts/utils/Strings.sol:58:9:
   |
58 |         buffer[0] = "0";

Do you know why this happened?

Thanks!

**Comment by leonardoalt** [comment]
Hi @acmRecife , great to hear!

Yes, when a property cannot be proved nor disproved by the underlying solver, the tool says "<something> might happen here". This means it's simply not sure, and expected for complicated properties and/or low timeout limits.

**Comment by blishko** [comment]
Hi @acmRecife, are you still experiencing any problems?
Or can we close this issue?

**Comment by acmRecife** [comment]
Hey, @blishko . I am not using SMTChecker right now. Thanks
