### ISSUE TITLE
"ProviderError: HttpProviderError" does not show error message

### ISSUE THREAD

**Issue by hiroshi-yamamoto-dublr** [ethereum/solidity#13637]
## Description

The error message for `ProviderError` needs to include `error.message`.

If I run the following code, and the contract deployment exceeds the block gas limit:

```solidity
    const contract = await MyContract.deploy({gasLimit: 3e7});
```

then I get

```
ProviderError: HttpProviderError
    at HttpProvider.request (/home/dublr/dublr/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at AutomaticSenderProvider.request (/home/dublr/dublr/node_modules/hardhat/src/internal/core/providers/accounts.ts:341:34)
    at AutomaticGasProvider.request (/home/dublr/dublr/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:135:34)
    at AutomaticGasPriceProvider.request (/home/dublr/dublr/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:153:36)
    at BackwardsCompatibilityProviderAdapter.send (/home/dublr/dublr/node_modules/hardhat/src/internal/core/providers/backwards-compatibility.ts:36:27)
    at EthersProviderWrapper.send (/home/dublr/dublr/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:48)
    at EthersProviderWrapper.<anonymous> (/home/dublr/dublr/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:31)
    at step (/home/dublr/dublr/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.next (/home/dublr/dublr/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at /home/dublr/dublr/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:23:71
```

However if I run the following code, the "exceeds block gas limit" error message is shown:

```solidity
    try {
        const contract = await MyContract.deploy({gasLimit: 3e7});
    } catch (e) {
        console.log(e.message);
        throw e;
    }
```

then I get

```
exceeds block gas limit
ProviderError: HttpProviderError
    at HttpProvider.request (/home/dublr/dublr/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at AutomaticSenderProvider.request (/home/dublr/dublr/node_modules/hardhat/src/internal/core/providers/accounts.ts:341:34)
    at AutomaticGasProvider.request (/home/dublr/dublr/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:135:34)
    at AutomaticGasPriceProvider.request (/home/dublr/dublr/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:153:36)
    at BackwardsCompatibilityProviderAdapter.send (/home/dublr/dublr/node_modules/hardhat/src/internal/core/providers/backwards-compatibility.ts:36:27)
    at EthersProviderWrapper.send (/home/dublr/dublr/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:48)
    at EthersProviderWrapper.<anonymous> (/home/dublr/dublr/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:31)
    at step (/home/dublr/dublr/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.next (/home/dublr/dublr/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at /home/dublr/dublr/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:23:71
```

## Environment

- Compiler version: 0.8.17
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client:
- Operating system: Linux

**Comment by cameel** [comment]
Hello. Thanks for reporting but this does not look like an issue in the compiler. First, it's a runtime error and the compiler does not run your code, it only produces the bytecode to be run. Second, the compiler does not produce these JS stack traces or error messages. This looks more like a problem with [ethers.js or one of its dependencies so I recommend asking there](https://github.com/ethers-io/ethers.js/discussions).

**Comment by ghost** [comment]
Nice bug
