### ISSUE TITLE
 for loop i=9;i>=0;i--  execution reverted: arithmetic underflow or overflow

### ISSUE THREAD

**Issue by pengsp** [ethereum/solidity#15325]
## Description

The for loop uses decrement and throws an exception if the decrement condition is used to be greater than or equal to 0 : ` Internal JSON-RPC error -- "execution reverted: arithmetic underflow or overflow"`
```
Error: call revert exception; VM Exception while processing transaction: reverted with panic code 17 [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="###method_name
 ###", errorArgs=[{"type":"BigNumber","hex":"0x11"}], errorName="Panic", errorSignature="Panic(uint256)", reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (index.js:231:23)
    at Logger.throwError (index.js:240:20)
    at Interface.decodeFunctionResult (interface.js:365:23)
    at Contract.eval (index.js:310:48)
    at Generator.next (<anonymous>)
    at fulfilled (index.js:22:58)
````
## Environment

- Compiler version:  0.8.26
## Steps to Reproduce

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract ForLoopExample {
    function decrement_gt0_ForLoop() public pure returns (uint) {
        uint sum = 0;
        for (uint i = 9; i > 0; i--) {
            // i>0 it's ok
            sum += i;
        }
        return sum; //return 45
    }
    function decrement_gte0_ForLoop() public pure returns (uint) {
        uint sum = 0;
        for (uint i = 9; i >= 0; i--) {
            // i>=0 , it's not working, call_exception: execution reverted: arithmetic underflow or overflow
            sum += i;
        }
        return sum; //return Internal JSON-RPC error -- "execution reverted: arithmetic underflow or overflow"
    }
    function increment_lt0_ForLoop() public pure returns (uint) {
        uint sum = 0;

        for (uint i = 0; i < 10; i++) {
            // it's ok
            sum += i;
        }
        return sum; //return 45
    }
    function increment_lte0_ForLoop() public pure returns (uint) {
        uint sum = 0;

        for (uint i = 0; i <= 10; i++) {
            // it's ok
            sum += i;
        }
        return sum; // return 55
    }
}


```

**Comment by nikola-matic** [comment]
Hi @pengsp. This isn't a bug, and behaves as it should. Namely, in the loop in question, the counter `i` will underflow in the last iteration, which will cause it to revert, as it ultimately should, since this is exactly the purpose of checked arithmetic by default (since 0.8.0). If you were to use a pre 0.8.0 version of solc, or if you were to wrap the arithmetic operations in an unchecked block, it would yield an infinite loop.
