### ISSUE TITLE
Invalid hex output generated by compiler

### ISSUE THREAD

**Issue by akhilss** [ethereum/solidity#1605]
Hi,

While compiling the AllParties.sol contract, the bytecode generated contains the underscore character. Since it is not a hex character, it cannot be deployed.  I believe it is because it is importing a library contract. 
I am using the soljson-v0.4.8+commit.60cc1668.js compiler and am able to reproduce the compiled output using the online compiler.

The zip contains all contracts.

[contracts.zip](https://github.com/ethereum/solidity/files/729051/contracts.zip)

**Comment by chriseth** [comment]
You are right, the behaviour is explained here: https://solidity.readthedocs.io/en/develop/miscellaneous.html#using-the-commandline-compiler

What is the behaviour you expect and why do you think this is a bug?

**Comment by akhilss** [comment]
Hi,

I was getting this error while deploying this contract. Since hte _ is invalid hex I had assumed it to be the problem. I guess the embark framework does not have special handling for libraries. I will rewriting the contract to avoid using the library key word to move forward.

error deploying contract: AllParties
Error: invalid argument 0: invalid hex
error deploying contracts
Error: Error: invalid argument 0: invalid hex
Error: Error: Error: invalid argument 0: invalid hex
    at /home/derisk/.nvm/versions/node/v7.4.0/lib/node_modules/embark/lib/deploy.js:74:25
    at /home/derisk/.nvm/versions/node/v7.4.0/lib/node_modules/embark/lib/deploy.js:133:16
    at Object.callback (/home/derisk/.nvm/versions/node/v7.4.0/lib/node_modules/embark/node_modules/web3/lib/web3/contract.js:220:21)
    at /home/derisk/.nvm/versions/node/v7.4.0/lib/node_modules/embark/node_modules/web3/lib/web3/method.js:142:25
    at /home/derisk/.nvm/versions/node/v7.4.0/lib/node_modules/embark/node_modules/web3/lib/web3/requestmanager.js:86:20
    at XMLHttpRequest.request.onreadystatechange (/home/derisk/.nvm/versions/node/v7.4.0/lib/node_modules/embark/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/derisk/.nvm/versions/node/v7.4.0/lib/node_modules/embark/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/derisk/.nvm/versions/node/v7.4.0/lib/node_modules/embark/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/derisk/.nvm/versions/node/v7.4.0/lib/node_modules/embark/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/derisk/.nvm/versions/node/v7.4.0/lib/node_modules/embark/node_modules/xhr2/lib/xhr2.js:469:24)

**Comment by chriseth** [comment]
Ah ok! Can this be closed then? Note that you can still use libraries if all functions you call are marked "internal".
