### ISSUE TITLE
Visual Studio Code: The Solidity Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#2759]
I am working on Win10 and getting this error from VSCode after installing the Solidity extension and then opening a .sol file:

```

[Error - 14:16:07] (node:10264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Path must be a string. Received null
[Error - 14:16:07] (node:10264) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
C:\Users\John Jackon\.vscode\extensions\JuanBlanco.solidity-0.0.27\node_modules\solc\soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path")

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at createPackage (C:\Users\John Jackon\.vscode\extensions\JuanBlanco.solidity-0.0.27\out\src\projectService.js:12:35)
    at createProjectPackage (C:\Users\John Jackon\.vscode\extensions\JuanBlanco.solidity-0.0.27\out\src\projectService.js:87:26)
    at Object.initialiseProject (C:\Users\John Jackon\.vscode\extensions\JuanBlanco.solidity-0.0.27\out\src\projectService.js:33:26)
    at SolcCompiler.compileSolidityDocumentAndGetDiagnosticErrors (C:\Users\John Jackon\.vscode\extensions\JuanBlanco.solidity-0.0.27\out\src\solcCompiler.js:108:87)
    at validate (C:\Users\John Jackon\.vscode\extensions\JuanBlanco.solidity-0.0.27\out\src\server.js:36:52)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\John Jackon\.vscode\extensions\JuanBlanco.solidity-0.0.27\out\src\server.js:125:26)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[Error - 14:16:09] Connection to server got closed. Server will not be restarted.

```

**Comment by chriseth** [comment]
This seems to be a problem in the VSCode extension. The relevant github repository is here: https://github.com/juanfranblanco/vscode-solidity/issues

Please report the issue there.

Thanks!
