### ISSUE TITLE
Online compiler throws when using wrong number of args in base constructor

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#364]
It only happens when base constructor is called in initializer list.

```
contract C {
    function C(){}
}

contract D is C {
    function D() C(5){}

}
```

Not when using `new C(5);` or `contract D is C(4)`; in those cases you get the correct error.

`Solidity version: 0.2.0-67c855c5/.-Emscripten/clang/int`

Dump:

```
Uncaught JavaScript exception:
abort(7) at Error
    at jsStackTrace (https://chriseth.github.io/browser-solidity/bin/soljson-latest.js:1:20800)
    at stackTrace (https://chriseth.github.io/browser-solidity/bin/soljson-latest.js:1:20983)
    at abort (https://chriseth.github.io/browser-solidity/bin/soljson-latest.js:19:16134)
    at Array.Nzb (https://chriseth.github.io/browser-solidity/bin/soljson-latest.js:12:84538)
    at Object.mzb [as dynCall_ii] (https://chriseth.github.io/browser-solidity/bin/soljson-latest.js:12:82199)
    at invoke_ii (https://chriseth.github.io/browser-solidity/bin/soljson-latest.js:1:1295698)
    at Array.i6 (https://chriseth.github.io/browser-solidity/bin/soljson-latest.js:8:719476)
    at Object.Bzb [as dynCall_viii] (https://chriseth.github.io/browser-solidity/bin/soljson-latest.js:12:83756)
    at invoke_viii (https://chriseth.github.io/browser-solidity/bin/soljson-latest.js:1:1298444)
    at Array.g6 (https://chriseth.github.io/browser-solidity/bin/soljson-latest.js:8:715608)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by VoR0220** [comment]
hmmmmm....it would seem that you would need to declare the contract inside the function. So I think it's correct to throw an error in this particular instance (though it should still throw an error here I agree), going to definitely have to fix this as it does the same even when I declare it as such: 

```
contract C {
    function C(){}
}

contract D is C {
    function D(int arg) {C(arg);}

}
```

**Comment by androlo** [comment]
Yes. The bug-report is of the compiler throwing rather then returning an error, like it does in the other two cases.

**Comment by VoR0220** [comment]
so we have a two part bug going on here. Alright. Thanks for the update. Let's see what we can do.
