### ISSUE TITLE
YUL optimizer: Exception thrown by CommonSubexpressionEliminator

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#5374]
## Description

The following YUL contract makes the YUL optimizer (CSE) throw an exception:

```
{
    let r
    r := 1
    function f(x, y) -> a, b {    b := 4
    }}
//
```

The relevant portion of the exception stack is:
```
    #11 0x643c96 in void boost::throw_exception<dev::yul::OptimizerException>(dev::yul::OptimizerException const&) /usr/local/include/bo
ost/throw_exception.hpp:69:5
    #12 0x714845 in dev::yul::CommonSubexpressionEliminator::visit(boost::variant<dev::solidity::assembly::FunctionalInstruction, dev::s
olidity::assembly::FunctionCall, dev::solidity::assembly::Identifier, dev::solidity::assembly::Literal>&) /src/solidity/libyul/optimiser
/CommonSubexpressionEliminator.cpp:64:4
    #13 0x776645 in dev::yul::DataFlowAnalyzer::operator()(dev::solidity::assembly::Assignment&) /src/solidity/libyul/optimiser/DataFlow
Analyzer.cpp:45:2
    #14 0x776315 in walkVector<std::__1::vector<boost::variant<dev::solidity::assembly::ExpressionStatement, dev::solidity::assembly::In
struction, dev::solidity::assembly::Label, dev::solidity::assembly::StackAssignment, dev::solidity::assembly::Assignment, dev::solidity:
:assembly::VariableDeclaration, dev::solidity::assembly::FunctionDefinition, dev::solidity::assembly::If, dev::solidity::assembly::Switc
h, dev::solidity::assembly::ForLoop, dev::solidity::assembly::Block>, std::__1::allocator<boost::variant<dev::solidity::assembly::Expres
sionStatement, dev::solidity::assembly::Instruction, dev::solidity::assembly::Label, dev::solidity::assembly::StackAssignment, dev::soli
dity::assembly::Assignment, dev::solidity::assembly::VariableDeclaration, dev::solidity::assembly::FunctionDefinition, dev::solidity::as
sembly::If, dev::solidity::assembly::Switch, dev::solidity::assembly::ForLoop, dev::solidity::assembly::Block> > > &> /src/solidity/liby
ul/optimiser/ASTWalker.h:117:4
    #15 0x776315 in dev::yul::ASTModifier::operator()(dev::solidity::assembly::Block&) /src/solidity/libyul/optimiser/ASTWalker.cpp:156
    #16 0x77c6d3 in dev::yul::DataFlowAnalyzer::operator()(dev::solidity::assembly::Block&) /src/solidity/libyul/optimiser/DataFlowAnaly
zer.cpp:120:15
```

## Environment

- Compiler version: latest develop commit
- Framework/IDE (e.g. Truffle or Remix): na
- EVM execution environment / backend / blockchain client: na
- Operating system: Ubuntu 16.04

## Steps to Reproduce

- Run the `yulopti` binary on the contract above
- In the interactive step, choose the `c` (CSE) option

**Comment by chriseth** [comment]
A bugfix was merged today - can you try again please?

**Comment by leonardoalt** [comment]
I tried it with updated code and confirm it's fixed.
Please reopen if the error persists.

**Comment by bshastry** [comment]
Hi @chriseth @leonardoalt 

ack, I can confirm that this issue cannot be reproduced with the later commit.
