### ISSUE TITLE
Segmentation fault running solidity.

### ISSUE THREAD

**Issue by tymat** [ethereum/solidity#571]
**Solidity Version** `0.3.2-4b445b89/Release-Darwin/appleclang/JIT`
**Operating System** OS X 

Installed from homebrew.  Sample codes compile just fine using browser solidity.  

```
# gdb --args solc --bin contracts/Gold.sol
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin15.4.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from solc...done.
(gdb) run
Starting program: /usr/local/bin/solc --bin contracts/Gold.sol

Program received signal SIGSEGV, Segmentation fault.
0x00000001001b4280 in dev::solidity::CompilerContext::CompilerContext(dev::solidity::CompilerContext&&) () from /usr/local/Cellar/cpp-ethereum/1.2.4/lib/libsolidity.dylib

(gdb) bt
#0  0x00000001001b4280 in dev::solidity::CompilerContext::CompilerContext(dev::solidity::CompilerContext&&) () from /usr/local/Cellar/cpp-ethereum/1.2.4/lib/libsolidity.dylib
#1  0x00000001001a9cb4 in dev::solidity::Compiler::compileContract(dev::solidity::ContractDefinition const&, std::__1::map<dev::solidity::ContractDefinition const*, dev::eth::Assembly const*, std::__1::less<dev::solidity::ContractDefinition const*>, std::__1::allocator<std::__1::pair<dev::solidity::ContractDefinition const* const, dev::eth::Assembly const*> > > const&) () from /usr/local/Cellar/cpp-ethereum/1.2.4/lib/libsolidity.dylib
#2  0x00000001001dc107 in dev::solidity::CompilerStack::compileContract(bool, unsigned int, dev::solidity::ContractDefinition const&, std::__1::map<dev::solidity::ContractDefinition const*, dev::eth::Assembly const*, std::__1::less<dev::solidity::ContractDefinition const*>, std::__1::allocator<std::__1::pair<dev::solidity::ContractDefinition const* const, dev::eth::Assembly const*> > >&) () from /usr/local/Cellar/cpp-ethereum/1.2.4/lib/libsolidity.dylib
#3  0x00000001001dbf85 in dev::solidity::CompilerStack::compile(bool, unsigned int) () from /usr/local/Cellar/cpp-ethereum/1.2.4/lib/libsolidity.dylib
#4  0x0000000100007c4e in dev::solidity::CommandLineInterface::processInput() ()
#5  0x000000010001efe9 in main ()
(gdb)
```

**Comment by VoR0220** [comment]
Known problem. See #490 and #502 and #486 . Also see the area where it's happening #570

**Comment by VoR0220** [comment]
closing as replicated.
