### ISSUE TITLE
Memory leak of 464 bytes leaked in 7 allocation sites.

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#5882]
## Description

(Found by ossfuzz: issue number 12673)

While processing the following Soldity contract, the Solidity compiler leaks 464 bytes of memory across 7 allocation sites

```
contract C{function f()returns(C){f().r;}}
```

## Environment

- Compiler version: Latest develop commit
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 LTS

## Steps to Reproduce

I had to compile the solfuzzer target with ASan first, like so

```
$ mkdir solidity_build
$ cmake -DUSE_Z3=OFF -DUSE_CVC4=OFF -DCMAKE_CXX_FLAGS="-fsanitize=address" ../solidity
$ make solfuzzer -j
```

and then I replayed the contract like so (shown below are the first few lines of a much bigger leak report output by ASan:

```
$ ./solfuzzer <contract.sol>

=================================================================
==21302==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 336 byte(s) in 3 object(s) allocated from:
    #0 0x7f45c904b458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x561dfa998044 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<unsigned long const, std::pair<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0>, unsigned int> > > >::allocate(unsigned long, void const*) (/home/bhargava/work/github/solidity/build/test/tools/solfuzzer+0xc5d044)
    #2 0x561dfa982c5f in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<unsigned long const, std::pair<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0>, unsigned int> > > > >::allocate(std::allocator<std::_Rb_tree_node<std::pair<unsigned long const, std::pair<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0>, unsigned int> > > >&, unsigned long) (/home/bhargava/work/github/solidity/build/test/tools/solfuzzer+0xc47c5f)
...
```

**Comment by axic** [comment]
Keeping discussion in #6011.
