### ISSUE TITLE
Issue obtaining solc

### ISSUE THREAD

**Issue by mesudip** [ethereum/solidity#7090]
**Version** : 5.0.20 and later (or previous versions when specifying  solc version in `truffle-config.js`)

**OS:**
```
NAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19"
VERSION_ID="19"
VERSION_CODENAME=tara
UBUNTU_CODENAME=bionic
```

**Error output:**
```
sudip@Linux-Mint:~/Documents/wallet-server$ npm install truffle@5.0.20

> truffle@5.0.20 postinstall /home/sudip/Documents/wallet-server/node_modules/truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
- Downloading compiler. Attempt #1
- Downloading compiler. Attempt #2
- Downloading compiler. Attempt #3

/home/sudip/Documents/wallet-server/node_modules/truffle/scripts/postinstall.js:22
  throw error;
  ^

Error: Error while attempting to download and cache solc 0.5.8: Command failed: node ./build/cli.bundled.js obtain --solc=0.5.8
- Fetching solc version list from solc-bin. Attempt #1
- Downloading compiler. Attempt #1
- Downloading compiler. Attempt #2
- Downloading compiler. Attempt #3
 at postinstallObtain (/home/sudip/Documents/wallet-server/node_modules/truffle/scripts/postinstall.js:13:11)
    at Object.<anonymous> (/home/sudip/Documents/wallet-server/node_modules/truffle/scripts/postinstall.js:20:3)
```

**Comment by leonardoalt** [comment]
Hi @mesudip ,
Have you tried asking the Truffle folks (https://github.com/trufflesuite/truffle/)? It looks like this is coming from Truffle code.

**Comment by chriseth** [comment]
The repository can be offline from time to time, but it seems to be online now - so maybe just try again?

**Comment by axic** [comment]
This doesn't seem to be a real issue. Maybe in the long term truffle could retrieve solc from IPFS.
