### ISSUE TITLE
[solc] Non reproducible Segfault while computing swarm hash

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7499]
## Description

```
pragma experimental SMTChecker;
contract C
{
    address e;
    bool b
;    uint c;
    function f(uint x) public {
 
   address e;
    bool b
;    uint g; {int Y;
     5 
;     bool e;   
   
{37;
 int A0;     uint c;
  uint Y;
 }}{          bool e;

    uint c    
;{int Y;
     4 
;     bool e;   
   
{38;
 int A0;     uint c;
  uint Y;
 }}{          bool e;

    uint c    
; }       }         {       
 {    bool 
  b;  0;
 int A0;     bool e;
      uint Y;
     }
    uint c;
     }
          }
}
//0):!AS\00x\00
```

crashes here https://github.com/ethereum/solidity/blob/8847647547450090c4ea841b71dc97b3ba4f589f/libdevcore/SwarmHash.cpp#L98

due to a memory corruption detected by libc++ implementation of malloc

Partial stack trace

```
*** Error in `/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_solidity_1f25b1a3d7db88ab74f844e0dfe8ca4f7cd73cd2/revisions/solc_noopt_ossfuzz': corrupted double-linked list (not small): 0x000000000547b710 ***
...
#5 0x7fa0987e0cdd in _int_malloc /build/glibc-LK5gWL/glibc-2.23/malloc/malloc.c:3450
--
  | #6 0x7fa0987e3183 in __libc_malloc /build/glibc-LK5gWL/glibc-2.23/malloc/malloc.c:2913
  | #7 0x1f41084 in operator new(unsigned long)
  | #8 0x108b452 in __libcpp_allocate /usr/local/include/c++/v1/new:253:10
  | #9 0x108b452 in allocate /usr/local/include/c++/v1/memory:1854:37
  | #10 0x108b452 in allocate /usr/local/include/c++/v1/memory:1571:21
  | #11 0x108b452 in __split_buffer /usr/local/include/c++/v1/__split_buffer:318:29
  | #12 0x108b452 in std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::__append(unsigned long, unsigned char const&) /usr/local/include/c++/v1/vector:1111:53
  | #13 0x108a63f in resize /usr/local/include/c++/v1/vector:2033:15
  | #14 0x108a63f in (anonymous namespace)::chunkHash(dev::vector_ref<unsigned char const>, bool) solidity/libdevcore/SwarmHash.cpp:98:13
  | #15 0x1089bcb in dev::bzzr1Hash(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) solidity/libdevcore/SwarmHash.cpp:115:9
  | #16 0x7b5dd3 in dev::bzzr1Hash(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) solidity/libdevcore/SwarmHash.h:37:9
```

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):

## Steps to Reproduce

TBD

**Comment by chriseth** [comment]
@bshastry I was not able to reproduce this right away - is it still an issue?

**Comment by bshastry** [comment]
I could not either. Will close issue and reopen if it could be reliably reproduced.
