### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by euri10** [ethereum/solidity#772]
I dunno if I'm using it wrongly or if this is normal, apologies if it work as intended

```
➜  ddn git:(master) ✗ solc --version
solc, the solidity compiler commandline interface
Version: 0.3.5-6610add6/Debug-Linux/g++/Interpreter
```

```
➜  ddn git:(master) ✗ gdb --args solc --optimize --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,userdoc  contracts/bytesToString.sol
GNU gdb (Debian 7.11.1-2) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from solc...done.
gdb-peda$ run
Starting program: /usr/local/bin/solc --optimize --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,userdoc contracts/bytesToString.sol
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
[----------------------------------registers-----------------------------------]
RAX: 0x5614d0 ("r than 3. Should not reach here.")
RBX: 0x646c756f6853202e ('. Should')
RCX: 0x7ffff55a0fb1 (<__memcmp_sse4_1+4817>:    movdqu xmm2,XMMWORD PTR [rdi-0x1b])
RDX: 0x1b
RSI: 0x538ddb --> 0x538df0006e640000
RDI: 0x33206e616874208d
RBP: 0x1b
RSP: 0x7fffffffd158 --> 0x7ffff5e34588 (<_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_+40>:      test   eax,eax)
RIP: 0x7ffff55a0fb1 (<__memcmp_sse4_1+4817>:    movdqu xmm2,XMMWORD PTR [rdi-0x1b])
R8 : 0x5880e0 --> 0x588030 --> 0x0
R9 : 0x588900 --> 0x1
R10: 0x7ffff6c3fc3c (<std::pair<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~pair()+28>:    nop)
R11: 0x7ffff55c49c0 --> 0xfffdc1f0fffdbf1f
R12: 0x7fffffffd5b0 --> 0x7fffffffd5c0 --> 0x7f00656d616e
R13: 0x1
R14: 0x0
R15: 0x0
EFLAGS: 0x10207 (CARRY PARITY adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff55a0fa2 <__memcmp_sse4_1+4802>:       pxor   xmm2,xmm1
   0x7ffff55a0fa6 <__memcmp_sse4_1+4806>:       ptest  xmm0,xmm2
   0x7ffff55a0fab <__memcmp_sse4_1+4811>:       jae    0x7ffff55a12c8 <__memcmp_sse4_1+5608>
=> 0x7ffff55a0fb1 <__memcmp_sse4_1+4817>:       movdqu xmm2,XMMWORD PTR [rdi-0x1b]
   0x7ffff55a0fb6 <__memcmp_sse4_1+4822>:       movdqu xmm1,XMMWORD PTR [rsi-0x1b]
   0x7ffff55a0fbb <__memcmp_sse4_1+4827>:       mov    dl,0xe5
   0x7ffff55a0fbd <__memcmp_sse4_1+4829>:       pxor   xmm2,xmm1
   0x7ffff55a0fc1 <__memcmp_sse4_1+4833>:       ptest  xmm0,xmm2
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffd158 --> 0x7ffff5e34588 (<_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_+40>:     test   eax,eax)
0008| 0x7fffffffd160 --> 0x7fffffffd1a0 --> 0x7ffff6da2b51 --> 0x6e00637273006469 ('id')
0016| 0x7fffffffd168 --> 0x7fffffffdd28 --> 0x7fff00000000
0024| 0x7fffffffd170 --> 0x7fffffffd190 --> 0x7fffffffd1c0 --> 0x7fffffffd200 --> 0x7fffffffd250 --> 0x7fffffffd290 (--> ...)
0032| 0x7fffffffd178 --> 0x4c15bf (<std::operator< <char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+35>:  )
0040| 0x7fffffffd180 --> 0x539560 --> 0x538dc0 ("contracts/bytesToString.sol")
0048| 0x7fffffffd188 --> 0x5614d0 ("r than 3. Should not reach here.")
0056| 0x7fffffffd190 --> 0x7fffffffd1c0 --> 0x7fffffffd200 --> 0x7fffffffd250 --> 0x7fffffffd290 --> 0x7fffffffd3b0 (--> ...)
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
__memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:1324
1324    ../sysdeps/x86_64/multiarch/memcmp-sse4.S: No such file or directory.
```

**Comment by euri10** [comment]
well I think it's a duplicate of https://github.com/ethereum/solidity/issues/742
since having only ast is what makes it crash

```
➜  ddn git:(master) ✗ gdb --args solc --optimize --combined-json ast contracts/bytesToString.sol
GNU gdb (Debian 7.11.1-2) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from solc...done.
gdb-peda$ run
Starting program: /usr/local/bin/solc --optimize --combined-json ast contracts/bytesToString.sol
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
[----------------------------------registers-----------------------------------]
RAX: 0x540300 ("r than 3. Should not reach here.")
RBX: 0x646c756f6853202e ('. Should')
RCX: 0x7ffff55a0fb1 (<__memcmp_sse4_1+4817>:    movdqu xmm2,XMMWORD PTR [rdi-0x1b])
RDX: 0x1b
RSI: 0x53872b --> 0x539060006e640000
RDI: 0x33206e616874208d
RBP: 0x1b
RSP: 0x7fffffffd198 --> 0x7ffff5e34588 (<_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_+40>:      test   eax,eax)
RIP: 0x7ffff55a0fb1 (<__memcmp_sse4_1+4817>:    movdqu xmm2,XMMWORD PTR [rdi-0x1b])
R8 : 0x58a1a0 --> 0x58a0f0 --> 0x0
R9 : 0x58a100 --> 0x589640 --> 0x0
R10: 0x7ffff6c3fc3c (<std::pair<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~pair()+28>:    nop)
R11: 0x7ffff55c49c0 --> 0xfffdc1f0fffdbf1f
R12: 0x7fffffffd5f0 --> 0x7fffffffd600 --> 0x7f00656d616e
R13: 0x1
R14: 0x0
R15: 0x0
EFLAGS: 0x10207 (CARRY PARITY adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff55a0fa2 <__memcmp_sse4_1+4802>:       pxor   xmm2,xmm1
   0x7ffff55a0fa6 <__memcmp_sse4_1+4806>:       ptest  xmm0,xmm2
   0x7ffff55a0fab <__memcmp_sse4_1+4811>:       jae    0x7ffff55a12c8 <__memcmp_sse4_1+5608>
=> 0x7ffff55a0fb1 <__memcmp_sse4_1+4817>:       movdqu xmm2,XMMWORD PTR [rdi-0x1b]
   0x7ffff55a0fb6 <__memcmp_sse4_1+4822>:       movdqu xmm1,XMMWORD PTR [rsi-0x1b]
   0x7ffff55a0fbb <__memcmp_sse4_1+4827>:       mov    dl,0xe5
   0x7ffff55a0fbd <__memcmp_sse4_1+4829>:       pxor   xmm2,xmm1
   0x7ffff55a0fc1 <__memcmp_sse4_1+4833>:       ptest  xmm0,xmm2
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffd198 --> 0x7ffff5e34588 (<_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_+40>:     test   eax,eax)
0008| 0x7fffffffd1a0 --> 0x7fffffffd1e0 --> 0x7ffff6da2b51 --> 0x6e00637273006469 ('id')
0016| 0x7fffffffd1a8 --> 0x7fffffffdd68 --> 0x7fff00000000
0024| 0x7fffffffd1b0 --> 0x7fffffffd1d0 --> 0x7fffffffd200 --> 0x7fffffffd240 --> 0x7fffffffd290 --> 0x7fffffffd2d0 (--> ...)
0032| 0x7fffffffd1b8 --> 0x4c15bf (<std::operator< <char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+35>:  )
0040| 0x7fffffffd1c0 --> 0x539190 --> 0x538710 ("contracts/bytesToString.sol")
0048| 0x7fffffffd1c8 --> 0x540300 ("r than 3. Should not reach here.")
0056| 0x7fffffffd1d0 --> 0x7fffffffd200 --> 0x7fffffffd240 --> 0x7fffffffd290 --> 0x7fffffffd2d0 --> 0x7fffffffd3f0 (--> ...)
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
__memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:1324
1324    ../sysdeps/x86_64/multiarch/memcmp-sse4.S: No such file or directory.
gdb-peda$ bt
#0  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:1324
#1  0x00007ffff5e34588 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000004c15bf in std::operator< <char, std::char_traits<char>, std::allocator<char> > (__lhs=<error: Cannot access memory at address 0x33206e6168742072>, __rhs="contracts/bytesToString.sol") at /usr/include/c++/5/bits/basic_string.h:4989
#3  0x00000000004c56a9 in std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator() (this=0x7fffffffdd60, __x=<error: Cannot access memory at address 0x33206e6168742072>, __y="contracts/bytesToString.sol")
    at /usr/include/c++/5/bits/stl_function.h:387
#4  0x00007ffff6c410a3 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >::_M_lower_bound (this=0x7fffffffdd60, __x=0x5402e0, __y=0x7fffffffdd68, __k="contracts/bytesToString.sol") at /usr/include/c++/5/bits/stl_tree.h:1644
#5  0x00007ffff6c40993 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >::find (this=0x7fffffffdd60, __k="contracts/bytesToString.sol") at /usr/include/c++/5/bits/stl_tree.h:2308
#6  0x00007ffff6c40425 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >::count (this=0x7fffffffdd60, __x="contracts/bytesToString.sol") at /usr/include/c++/5/bits/stl_map.h:892
#7  0x00007ffff6c3b124 in dev::solidity::ASTJsonConverter::sourceLocationToString[abi:cxx11](dev::SourceLocation const&) const (this=0x7fffffffdd90, _location=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/ast/ASTJsonConverter.cpp:79
#8  0x00007ffff6c3acd7 in dev::solidity::ASTJsonConverter::addJsonNode (this=0x7fffffffdd90, _node=..., _nodeName="ElementaryTypeName", _list=..., _hasChildren=0x0) at /home/lotso/webthree-umbrella/solidity/libsolidity/ast/ASTJsonConverter.cpp:55
#9  0x00007ffff6c3c282 in dev::solidity::ASTJsonConverter::visit (this=0x7fffffffdd90, _node=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/ast/ASTJsonConverter.cpp:161
#10 0x00007ffff6c91768 in dev::solidity::ElementaryTypeName::accept (this=0x536f40, _visitor=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/../libsolidity/ast/AST_accept.h:302
#11 0x00007ffff6c91282 in dev::solidity::VariableDeclaration::accept (this=0x537000, _visitor=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/../libsolidity/ast/AST_accept.h:221
#12 0x00007ffff6c0cf70 in dev::solidity::ASTNode::listAccept<std::shared_ptr<dev::solidity::VariableDeclaration> > (_list=std::vector of length 1, capacity 1 = {...}, _visitor=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/../libsolidity/ast/AST.h:71
#13 0x00007ffff6c90f05 in dev::solidity::ParameterList::accept (this=0x537090, _visitor=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/../libsolidity/ast/AST_accept.h:172
#14 0x00007ffff6c91096 in dev::solidity::FunctionDefinition::accept (this=0x53a840, _visitor=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/../libsolidity/ast/AST_accept.h:194
#15 0x00007ffff6c0b71e in dev::solidity::ASTNode::listAccept<std::shared_ptr<dev::solidity::ASTNode> > (_list=std::vector of length 2, capacity 2 = {...}, _visitor=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/../libsolidity/ast/AST.h:71
#16 0x00007ffff6c90948 in dev::solidity::ContractDefinition::accept (this=0x53e520, _visitor=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/../libsolidity/ast/AST_accept.h:75
#17 0x00007ffff6c0b71e in dev::solidity::ASTNode::listAccept<std::shared_ptr<dev::solidity::ASTNode> > (_list=std::vector of length 1, capacity 1 = {...}, _visitor=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/../libsolidity/ast/AST.h:71
#18 0x00007ffff6c9079d in dev::solidity::SourceUnit::accept (this=0x53e120, _visitor=...) at /home/lotso/webthree-umbrella/solidity/libsolidity/../libsolidity/ast/AST_accept.h:44
#19 0x00007ffff6c3f11d in dev::solidity::ASTJsonConverter::process (this=0x7fffffffdd90) at /home/lotso/webthree-umbrella/solidity/libsolidity/ast/ASTJsonConverter.cpp:495
#20 0x00007ffff6c3b602 in dev::solidity::ASTJsonConverter::json (this=0x7fffffffdd90) at /home/lotso/webthree-umbrella/solidity/libsolidity/ast/ASTJsonConverter.cpp:107
#21 0x00000000004b9887 in dev::solidity::CommandLineInterface::handleCombinedJSON (this=0x7fffffffe640) at /home/lotso/webthree-umbrella/solidity/solc/CommandLineInterface.cpp:697
#22 0x00000000004bbafd in dev::solidity::CommandLineInterface::outputCompilationResults (this=0x7fffffffe640) at /home/lotso/webthree-umbrella/solidity/solc/CommandLineInterface.cpp:870
#23 0x00000000004bad3f in dev::solidity::CommandLineInterface::actOnInput (this=0x7fffffffe640) at /home/lotso/webthree-umbrella/solidity/solc/CommandLineInterface.cpp:780
#24 0x00000000004a9ce2 in main (argc=0x5, argv=0x7fffffffe8c8) at /home/lotso/webthree-umbrella/solidity/solc/main.cpp:38
#25 0x00007ffff5479730 in __libc_start_main (main=0x4a9c53 <main(int, char**)>, argc=0x5, argv=0x7fffffffe8c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe8b8) at ../csu/libc-start.c:291
#26 0x00000000004a9ae9 in _start ()
```

**Comment by chriseth** [comment]
We are about to release a new version today, so please verify if that fixes it.
