### ISSUE TITLE
Error: spawnSync /bin/sh ENOBUFS

### ISSUE THREAD

**Issue by bohendo** [ethereum/solidity#8133]
## Description

I'm working w/in a lerna monorepo & I'm trying to consolidate a couple related contract sub-repos into one module. Compiling the consolidated contracts gives me the following error:

``` 
> waffle waffle.json

Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execSync (child_process.js:652:15)
    at /root/node_modules/ethereum-waffle/dist/compiler/compileNative.js:48:66
    at step (/root/node_modules/ethereum-waffle/dist/compiler/compileNative.js:32:23)
    at Object.next (/root/node_modules/ethereum-waffle/dist/compiler/compileNative.js:13:53)
    at /root/node_modules/ethereum-waffle/dist/compiler/compileNative.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/node_modules/ethereum-waffle/dist/compiler/compileNative.js:3:12)
    at compile (/root/node_modules/ethereum-waffle/dist/compiler/compileNative.js:43:16) {
  errno: 'ENOBUFS',
  code: 'ENOBUFS',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: [
    '-c',
    'solc --standard-json --allow-paths /root/modules/contracts/contracts,/root/node_modules'
  ],
  error: [Circular],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    <Buffer 7b 22 63 6f 6e 74 72 61 63 74 73 22 3a 7b 22 40 63 6f 6e 6e 65 78 74 2f 63 66 2d 61 64 6a 75 64 69 63 61 74 6f 72 2d 63 6f 6e 74 72 61 63 74 73 2f 63 ... 1114062 more bytes>,
    <Buffer >
  ],
  pid: 30,
  stdout: <Buffer 7b 22 63 6f 6e 74 72 61 63 74 73 22 3a 7b 22 40 63 6f 6e 6e 65 78 74 2f 63 66 2d 61 64 6a 75 64 69 63 61 74 6f 72 2d 63 6f 6e 74 72 61 63 74 73 2f 63 ... 1114062 more bytes>,
  stderr: <Buffer >
}
```

I reported this via [waffle issue 178](https://github.com/EthWorks/Waffle/issues/179) but upon further investigations it looks like it's not a problem w waffle itself but w the compiler inside the `ethereum/solc:0.5.15-alpine` image.

Compiling via truffle gives the same error when using compiler option: `version: "native"`:

```
Error: Error: spawnSync /bin/sh ENOBUFS
    at Object.compile (/root/node_modules/truffle/build/webpack:/packages/workflow-compile/legacy/index.js:80:1)
Truffle v5.1.6 (core: 5.1.6)
Node v12.13.0
```

I'm suspicious that I'm trying to compile too many contracts all at once and I'm getting some kind of out-of-memory issue.

I'm confident there aren't any circular dependencies lurking. Compilation works fine using solcjs, it's just the native compiler in alpine that's causing errors.

At the moment, a semi-working hack-around is to create two waffle.json files that each compile half the the contracts. The build succeeded when done in two steps like this before I integrated another chunk of contracts & now this third chunk always fails even if compiled separately (maybe bc it's importing contracts from the first two chunks?)

## Environment

- Compiler version: image `ethereum/solc:0.5.15-alpine` (also reproduced this issue in `ethereum/solc:0.5.11-alpine`)
- Target EVM version (as per compiler settings): constantinople
- Framework/IDE (e.g. Truffle or Remix): Waffle & Truffle
- EVM execution environment / backend / blockchain client: Haven't deployed contracts yet
- Operating system: Docker alpine

waffle.json

```
{
  "compiler": "native",
  "npmPath": "../../node_modules",
  "legacyOutput": true,
  "compilerOptions": {
    "evmVersion": "constantinople"
  },
  "sourcesPath": "./contracts"
}
```

## Steps to Reproduce

 - `git clone https://github.com/ConnextProject/indra.git`
 - `cd indra && git checkout b3856cf4`
 - `make contracts-native`

Sorry, no single solidity file seems to be to blame. Problem arises when compiling lots of contracts & the above project will repro the error reliably. First run will take a while since it needs to download lots of dependencies but subsequent runs of `make contracts-native` will go much more quickly.

**Comment by chriseth** [comment]
Thanks for reporting! Unfortunately, there is not much to read from the error messages. How much memory does the machine have you are running this on? What happens if you run the compiler directly without truffle or waffle?

ENOBUFS does not sound like a problem with the memory used by the compiler, but rather with the buffers used to send input and output back and forth. Maybe you selected too much output from the compiler and nodejs cannot handle it?

**Comment by chriseth** [comment]
Closing due to inactivity. Please re-open if you have further questions or information.

**Comment by lmahanand** [comment]
I am trying to compile smart contracts but it has resulted in below mentioned buffer space related error:

```
> Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol
> Compiling openzeppelin-solidity/contracts/utils/ReentrancyGuard.sol
Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (internal/child_process.js:1045:20)
    at spawnSync (child_process.js:597:24)
    at execSync (child_process.js:642:15)

```

Is anyone able to solve this issue?

**Comment by bohendo** [comment]
This issue is indeed an issue w the buffer size between a node process & it's solc child process being too small.
For those using waffle, the buffer size limit will be increased once [PR 205](https://github.com/EthWorks/Waffle/pull/205) is merged/published.

**Comment by Zbozi** [comment]
Worked around the error by setting `docker:false` int the `truffle-config.js`.
- node v14.3.0
- Truffle v5.1.26
- solc v0.6.1

**Comment by gatsbyz** [comment]
`docker:false` in `truffle-config.js` works!

defined [here](https://trufflesuite.com/docs/truffle/reference/configuration/#solc). 
```
docker: <boolean>, // Use a version obtained through docker
```
