### ISSUE TITLE
comment lines causing syntax error

### ISSUE THREAD

**Issue by mike80439** [ethereum/solidity#932]
This stripped-down contract causes a syntax error:

contract Test2 {
  address owner;
  function Test2(){
    owner = msg.sender;
  }
//  function doSomeStuff(){
//    string memory s = "xyz";
//  }
}

Removal of the "//" characters fixes.

/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/index.js:39
      throw e;
      ^
SyntaxError: Expected "{", "}", any character, comment, end of line or whitespace but end of input found. Line: 11, Column: 1
    at peg$buildException (/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/build/imports_parser.js:423:14)
    at Object.peg$parse [as parse](/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/build/imports_parser.js:3349:13)
    at Object.module.exports.parse (/usr/local/lib/node_modules/truffle/node_modules/solidity-parser/index.js:34:23)
    at /usr/local/lib/node_modules/truffle/lib/profiler.js:134:36
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:442:12)

**Comment by chriseth** [comment]
Are you sure this is a solidity issue? The error message seems like it is an error of the solidity parser built into truffle.

**Comment by mike80439** [comment]
Other than creating the test case, I haven't investigated. Go ahead and
close if you think it's truffle. Thanks.
