### ISSUE TITLE
splitSources.py can't handle invalid UTF-8 sequences

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#9710]
## Steps to Reproduce
```bash
scripts/splitSources.py test/libsolidity/syntaxTests/string/invalid_utf8_sequence.sol
```
```
Traceback (most recent call last):
  File "scripts/splitSources.py", line 51, in <module>
    lines = open(filePath, mode='r', encoding='utf8').read().splitlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 36: invalid start byte
```

## Description
The command above is executed by `scripts/ASTImportTest.sh` as a part of our command line tests. It's just preprocessing before the actual test.

It's still possible to split a multi-source file even if it contains invalid UTF-8 sequences so it's better to do so and let the compiler fail down the line instead of having two different layers where things can fail in different ways.

## Environment
- Compiler version: 0.7.1-develop.2020.8.31+commit.8c8eca3e.Linux.g++

**Comment by nishant-sachdeva** [comment]
I ran the command `scripts/splitSources.py test/libsolidity/syntaxTests/string/invalid_utf8_sequence.sol` 
The error I got is 
>UnicodeDecodeError in 'test/libsolidity/syntaxTests/string/invalid_utf8_sequence.sol': 'utf-8' codec can't decode byte 0xc0 in position 36: invalid start byte
This is expected for some tests containing invalid utf8 sequences. Exception will be ignored.

@cameel Has this issue been worked on already ? Or should we look to further improve this error statement

**Comment by cameel** [comment]
The issue is still relevant. The script still does not split files containing invalid UTF-8 and produces the `UnicodeDecodeError`. #9715 simply made it catch the exception and report the problem in a nicer way but it's still a problem.

I actually have a branch with a fix. I rebased it now: [`fix-unicode-splitting`](https://github.com/ethereum/solidity/tree/fix-unicode-splitting). I remember that I just ran into some small problem and never had time to finish it. Feel free to take it over.

**Comment by nikola-matic** [comment]
@cameel the example you mentioned doesn't contain invalid UTF-8 characters - all of the characters present in that file are part of the UTF-8 character set; the issue here is that the file is not UTF-8 encoded, so instead of `À` being encoded into `0xc380`, it ends up as `0xc0` which is IEC_8859-1 (or Latin-1 in Unicode). If you convert the file to UTF-8 encoding, the script will happily split the sources. So my question is - what do we want to achieve here? Support multiple input file encodings, or just UTF-8?

**Comment by cameel** [comment]
> the example you mentioned doesn't contain invalid UTF-8 characters - all of the characters present in that file are part of the UTF-8 character set

They aren't. A sequence of bytes starting with `0xc0` is not an UTF-8 encoding of any Unicode character. The fact that in some other encoding it might map to a valid Unicode character is irrelevant here since Solidity only supports UTF-8.

> So my question is - what do we want to achieve here? Support multiple input file encodings, or just UTF-8?

Only UTF-8. The goal here is to make `splitSources.py` properly split files no matter what encoding they use, without assuming whether it's UTF-8, latin-1 or whatever else. My issue with the script currently is simply that it makes that assumption while it does not have to because it does not need to interpret the content. Or rather it only has to interpret a very small bit of it - the separator. As long as it can find the ASCII encoded `==== Source:` in there, it should be able to split the file without failing on a `UnicodeDecode` error.

**Comment by nikola-matic** [comment]
>They aren't. A sequence of bytes starting with `0xc0` is not an UTF-8 encoding of any Unicode character. The fact that in some other encoding it might map to a valid Unicode character is irrelevant here since Solidity only supports UTF-8.

What I meant to say was `doesn't contain invalid Unicode characters`, but yeah, `0xc0` is not valid UTF-8, however is valid Latin-1 encoding.

> Only UTF-8. The goal here is to make `splitSources.py` properly split files no matter what encoding they use, without assuming whether it's UTF-8, latin-1 or whatever else. My issue with the script currently is simply that it makes that assumption while it does not have to because it does not need to interpret the content. Or rather it only has to interpret a very small bit of it - the separator. As long as it can find the ASCII encoded `==== Source:` in there, it should be able to split the file without failing on a `UnicodeDecode` error.

I guess read in binary then and match and split by `==== Source:`? This would then allow us to pass it as is to the compiler, which will then be responsible for the failure instead of `splitSources.py`?

**Comment by cameel** [comment]
Yes. Exactly. The compiler will still report it as an error but at least it will get to the compiler. Right now we're filtering such files out before they have a chance to be compiled.
